DestineySoccerAcademy/Controllers/Gallery/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DestineySoccerAcademy.Controllers.Gallery
{
    [AllowAnonymous]
    public class PhotoController : Controller
    {
        // GET: Photo
        public ActionResult Index()
        {
            return View();
        }
    }
}

DestineySoccerAcademy/Controllers/Users/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;
using DestineySoccerAcademy.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace DestineySoccerAcademy.Controllers.Users
{
    //[Authorize(Roles = RoleName.CMSP), Authorize(Roles = RoleName.CMP)]
    public class ApplicationUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //public ActionResult GetPlayers()
        //{
        //    //var usersWithRoles = (from user in db.Users
        //    //                      from userRole in user.Roles
        //    //                      join role in db.Roles on userRole.RoleId equals
        //    //                      "24d83418-4f4e-4a25-bc8a-99dd1f9f9389"
        //    //                      select new ApplicationUser()
        //    //                      {
        //    //                          RoleName = role.Name
        //    //                      });

        //    //return View("List", db.Roles.Where(r => r.Name == "Players").ToList());
        //    //return View("List", db.Users.Where(r => r.Roles.Where(n => n.RoleId.All(r.Roles.id == "24d83418-4f4e-4a25-bc8a-99dd1f9f9389")));
        //}

        // GET: ApplicationUsers
        [AllowAnonymous]
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.CMSP))
                return View("List", db.Users.ToList());
            else if (User.IsInRole(RoleName.CMP))
            {
                return View("ReadOnlyList", db.Users.ToList());
                //GetPlayers();
            }
            else
                ViewBag.Message = string.Format("You don't have the Admin previlage for this");
                return View();
        }

        // GET: ApplicationUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,MobilePhone,Address,State,Country," +
            "Birthdate,Create_date,ProfilePhoto,Email,EmailConfirmed,PasswordHash," +
            "SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled," +
            "LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,MobilePhone,Address,State,Country," +
            "Birthdate,Create_date,ProfilePhoto,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber," +
            "PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DestineySoccerAcademy/Views/Shared/_Footer.cshtml
<div class=footer-type02>
    <div class=container>
        <div class=row>
            <a href="@Url.Action("Index", "Home")" class=footer-logo><img src=~/images/DESTINY.png alt=image></a>

            <div class=footer-container>
                <ul class=clearfix>
                    <li>
                        <a href=https://www.facebook.com/templatespoint.net class=bigsocial-link>
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href=https://twitter.com/ class=bigsocial-link target=_blank>
                            <i class="fa fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href=https://www.instagram.net/ class=bigsocial-link target=_blank>
                            <i class="fa fa-instagram"></i>
                        </a>
                    </li>

                </ul>

                <p>
                    <span class=uppercaseheading>address:</span><span class=red></span> Uwani, Enugu State, Nigeria.
                </p>

                <p><span class=uppercaseheading>call:</span> <span class=red>+234 8034352735</span></p>

            </div>
        </div>
    </div>
</div>

DestineySoccerAcademy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<html class=no-js lang="">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/css/layerslider.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/vendor.css" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <header class=header-main>
            <div class="header-lower clearfix">
                <div class=container>
                    <div class=row id="Navbar">
                        @Html.Partial("_Navbar")
                    </div>
                </div>
            </div>
        </header>


        <div id="body">
            @RenderBody()
        </div>


    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/vendor/modernizr.js"></script>
    <script src="~/Scripts/js/vendor/vendor.js"></script>
    <script src="~/Scripts/js/main.js"></script>
</body>

@Html.Partial("_Footer")

</html>

DestineySoccerAcademy/Views/Shared/_Navbar.cshtml
<h1 class=logo>
    <a href="@Url.Action("Index", "Home")"><img src=~/images/DESTINY.png alt=image></a>
</h1>
<div class=menubar>
    <nav class=navbar>
        <div class=nav-wrapper>
            <div class=navbar-header>
                <button type=button class=navbar-toggle>
                    <span class=sr-only>Toggle navigation</span>
                    <span class=icon-bar></span>
                </button>
            </div>
            <div class=nav-menu>
                <ul class="nav navbar-nav menu-bar">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <img src="@Url.Action("UserPhotos", "Home" )" height="48" width="48" />
                        </li>
                    }
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>

                    <li>
                        @Html.ActionLink("About Us", "About", "Home")
                    </li>

                    <li>
                        @Html.ActionLink("Gallery", "Index", "Photo")
                    </li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Activities", "Index", "Activities")</li>
}
                    @if (User.Identity.IsAuthenticated && User.IsInRole("CanManagePlayersACtivitiesBlogs"))
                    {
                        <li>@Html.ActionLink("Details", "Index", "ApplicationUsers")</li>
}
                    @if (User.Identity.IsAuthenticated && User.IsInRole("CanManagePlayersStaffACtivitiesBlogs"))
                    {
                        <li>@Html.ActionLink("Details", "Index", "ApplicationUsers")</li>
}

                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home")
                    </li>

                    @Html.Partial("_LoginPartial")

                </ul>
            </div>
        </div>
    </nav>
</div>